### ISSUE TITLE
Could you clarify on "cause some machines to butcher the fonts"

### ISSUE THREAD

**Issue by nextgenthemes** [DaAwesomeP/php-offline-fonts#2]
What are this machines? Because its its IE 8 that need the unhinted/hinted version and others work with the hinted/unhinted I would happily drop the one of the two and download the files.

Also if we would know what fonts are actually served to what clients by Google then we could actually do it ourselves just like google does, with static font files without this complicated caching and setup.

**Comment by DaAwesomeP** [comment]
1. The cache is because Google automatically updates the fonts to the latest version as the author releases it. It also serves files to the browsers without a need for a large library like browscap that would eat up memory in this situation.
2. The hinting/unhinting more applies to Operating System than browser.
3. This is designed to be a "set it once and never touch it again" type of system. Google will update the fonts and you will never know. Browsers will update and you will never know.
4. The biggest flaw with Google Fonts is that Google has set their cache headers to make the browser reload the font way to often. This means that the page can load and apply the font afterwards (mainly in Firefox).

If you're that worried than download the fonts and just make sure they work in the browsers that you want them to work in and on the operating systems that you want them to work in. I don't use this anymore because it's inefficient; the files that list the Use Agents will become too large. Also, your server must now sacrifice bandwidth to query Google every time a user in a new browser shows up. It's more of an idea than a polished library. **Just use the Google URL.** Their servers will most likely be faster than yours ever will.

**Comment by nextgenthemes** [comment]
Thanks for the infos. Well my whole point was to skip freaking google tracking. Why must everything be so complicated.

So you not really seem to know exactly when Google serves unhinted/hinted fonts to what OS's. I will probably end up using google URLs because I am not really up for a trail and error run. Maybe I some more info. I heard about this unhinter/hinted thing the first time today. When I download fonts form fontsquirrel or somewhere there is just one version of the font in all formats no unhinted and hinted versions.
